## Economic Data

### GDP

In [4]:
import numpy as np
import pandas as pd

In [454]:
# Want in a format of country / date / value - so can merge with visa dataframe

In [455]:
economic_data = pd.read_csv('/Users/laurengilson/Desktop/perm_data/GDP_data.csv')

In [456]:
economic_data.head()

,Series Name,Series Code,Country Name,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,GDP (current US$),NY.GDP.MKTP.CD,United States,USA,14477635000000,14718582000000,14418739000000,14964372000000,15517926000000,16155255000000,16691517000000,17427609000000,18120714000000,18624475000000,19390604000000,..
1,GDP (current US$),NY.GDP.MKTP.CD,Afghanistan,AFG,9747879531.86311,10109225813.6696,12439087076.7667,15856574731.4411,17804292964.1045,19907317065.6667,20561069558.2152,20484885119.7348,19907111418.9938,19046357714.4928,19543976895.4248,..
2,GDP (current US$),NY.GDP.MKTP.CD,Albania,ALB,10677324144.4289,12881353507.8539,12044208085.864,11926957254.6288,12890866742.6533,12319784886.2038,12776280961.155,13228247844.1247,11386931489.7968,11883682170.8236,13038538300.2644,..
3,GDP (current US$),NY.GDP.MKTP.CD,Algeria,DZA,134977087734.008,171000691877.714,137211039898.193,161207268655.392,200019057307.655,209058991952.125,209755003250.664,213810022462.428,165979277276.907,160129866569.935,167555280113.181,..
4,GDP (current US$),NY.GDP.MKTP.CD,American Samoa,ASM,520000000,563000000,678000000,576000000,574000000,644000000,641000000,643000000,661000000,653000000,634000000,..

In [457]:
# drop unnecessary columns 
economic_data.drop(['Series Name', 'Series Code', 'Country Name'], axis=1, inplace=True)

In [458]:
economic_data.head()

,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,USA,14477635000000,14718582000000,14418739000000,14964372000000,15517926000000,16155255000000,16691517000000,17427609000000,18120714000000,18624475000000,19390604000000,..
1,AFG,9747879531.86311,10109225813.6696,12439087076.7667,15856574731.4411,17804292964.1045,19907317065.6667,20561069558.2152,20484885119.7348,19907111418.9938,19046357714.4928,19543976895.4248,..
2,ALB,10677324144.4289,12881353507.8539,12044208085.864,11926957254.6288,12890866742.6533,12319784886.2038,12776280961.155,13228247844.1247,11386931489.7968,11883682170.8236,13038538300.2644,..
3,DZA,134977087734.008,171000691877.714,137211039898.193,161207268655.392,200019057307.655,209058991952.125,209755003250.664,213810022462.428,165979277276.907,160129866569.935,167555280113.181,..
4,ASM,520000000,563000000,678000000,576000000,574000000,644000000,641000000,643000000,661000000,653000000,634000000,..

In [459]:
for column in list(economic_data.columns):
    economic_data[column] = list(map(str, economic_data[column]))
    economic_data[column] = [x.replace('..', '0') for x in economic_data[column]]

In [460]:
#Assume 2018 is same as 2017 * 0.031 (expected to increase by 3.1%)
economic_data['2018 [YR2018]'] = economic_data['2017 [YR2017]'].astype(float) * 1.031

In [461]:
economic_data.head()

,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,USA,14477635000000,14718582000000,14418739000000,14964372000000,15517926000000,16155255000000,16691517000000,17427609000000,18120714000000,18624475000000,19390604000000,1.999171e+13
1,AFG,9747879531.86311,10109225813.6696,12439087076.7667,15856574731.4411,17804292964.1045,19907317065.6667,20561069558.2152,20484885119.7348,19907111418.9938,19046357714.4928,19543976895.4248,2.014984e+10
2,ALB,10677324144.4289,12881353507.8539,12044208085.864,11926957254.6288,12890866742.6533,12319784886.2038,12776280961.155,13228247844.1247,11386931489.7968,11883682170.8236,13038538300.2644,1.344273e+10
3,DZA,134977087734.008,171000691877.714,137211039898.193,161207268655.392,200019057307.655,209058991952.125,209755003250.664,213810022462.428,165979277276.907,160129866569.935,167555280113.181,1.727495e+11
4,ASM,520000000,563000000,678000000,576000000,574000000,644000000,641000000,643000000,661000000,653000000,634000000,6.536540e+08

In [462]:
## Put data in billions
for column in list(economic_data.columns)[1:]:
    economic_data[column] = economic_data[column].astype(float)/1000000000
    economic_data[column] = economic_data[column].fillna(0)

In [463]:
economic_data.tail(10)

,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
259,SSF,1051.369321,1205.113311,1146.185674,1366.254397,1550.965860,1633.377913,1739.842928,1826.903050,1665.066294,1543.178532,1669.767509,1721.530302
260,SSA,1050.333896,1204.146272,1145.339193,1365.285978,1549.900214,1632.318043,1738.514628,1825.559832,1663.688787,1541.751164,1668.269754,1719.986117
261,TSS,1051.369321,1205.113311,1146.185674,1366.254397,1550.965860,1633.377913,1739.842928,1826.903050,1665.066294,1543.178532,1669.767509,1721.530302
262,UMC,10773.556651,13162.323938,12690.751725,15369.774015,18371.179949,19712.282823,20992.414587,21716.519718,20219.305351,20124.279748,22182.784745,22870.451072
263,WLD,57953.304868,63574.889384,60267.069670,65965.875327,73316.778722,74993.708029,77098.794654,79188.461750,74916.086734,75997.380506,80737.576005,83240.440861
264,nan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
265,nan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
266,nan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
267,nan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
268,nan,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [464]:
# Drop last rows of nans
economic_data = economic_data[:-5]

In [465]:
economic_data.tail()

,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
259,SSF,1051.369321,1205.113311,1146.185674,1366.254397,1550.965860,1633.377913,1739.842928,1826.903050,1665.066294,1543.178532,1669.767509,1721.530302
260,SSA,1050.333896,1204.146272,1145.339193,1365.285978,1549.900214,1632.318043,1738.514628,1825.559832,1663.688787,1541.751164,1668.269754,1719.986117
261,TSS,1051.369321,1205.113311,1146.185674,1366.254397,1550.965860,1633.377913,1739.842928,1826.903050,1665.066294,1543.178532,1669.767509,1721.530302
262,UMC,10773.556651,13162.323938,12690.751725,15369.774015,18371.179949,19712.282823,20992.414587,21716.519718,20219.305351,20124.279748,22182.784745,22870.451072
263,WLD,57953.304868,63574.889384,60267.069670,65965.875327,73316.778722,74993.708029,77098.794654,79188.461750,74916.086734,75997.380506,80737.576005,83240.440861

In [466]:
# Round to 2dp
for column in list(economic_data.columns)[1:]:
    economic_data[column] = economic_data[column].apply(lambda x: round(x, 2))

In [467]:
economic_data.tail()

,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
259,SSF,1051.37,1205.11,1146.19,1366.25,1550.97,1633.38,1739.84,1826.90,1665.07,1543.18,1669.77,1721.53
260,SSA,1050.33,1204.15,1145.34,1365.29,1549.90,1632.32,1738.51,1825.56,1663.69,1541.75,1668.27,1719.99
261,TSS,1051.37,1205.11,1146.19,1366.25,1550.97,1633.38,1739.84,1826.90,1665.07,1543.18,1669.77,1721.53
262,UMC,10773.56,13162.32,12690.75,15369.77,18371.18,19712.28,20992.41,21716.52,20219.31,20124.28,22182.78,22870.45
263,WLD,57953.30,63574.89,60267.07,65965.88,73316.78,74993.71,77098.79,79188.46,74916.09,75997.38,80737.58,83240.44

In [468]:
# dict of new columns 
years = [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
col_list = list(economic_data.columns[1:])
new_cols = dict(zip(col_list, years))

In [469]:
# Change column head to fiscal years 
economic_data.rename(columns=new_cols, inplace=True)

In [470]:
economic_data

,Country Code,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,USA,14477.64,14718.58,14418.74,14964.37,15517.93,16155.25,16691.52,17427.61,18120.71,18624.47,19390.60,19991.71
1,AFG,9.75,10.11,12.44,15.86,17.80,19.91,20.56,20.48,19.91,19.05,19.54,20.15
2,ALB,10.68,12.88,12.04,11.93,12.89,12.32,12.78,13.23,11.39,11.88,13.04,13.44
3,DZA,134.98,171.00,137.21,161.21,200.02,209.06,209.76,213.81,165.98,160.13,167.56,172.75
4,ASM,0.52,0.56,0.68,0.58,0.57,0.64,0.64,0.64,0.66,0.65,0.63,0.65
5,AND,4.02,4.01,3.66,3.36,3.44,3.16,3.28,3.35,2.81,2.88,3.01,3.11
6,AGO,65.27,88.54,70.31,83.80,111.79,128.05,136.71,145.71,116.19,101.12,122.12,125.91
7,ATG,1.31,1.37,1.22,1.15,1.14,1.21,1.19,1.28,1.36,1.46,1.51,1.56
8,ARG,287.53,361.56,332.98,423.63,530.16,545.98,552.03,526.32,594.75,554.86,637.43,657.19
9,ARM,9.21,11.66,8.65,9.26,10.14,10.62,11.12,11.61,10.55,10.55,11.54,11.89
10,ABW,2.62,2.75,2.50,2.39,2.55,2.53,2.58,2.65,2.69,2.65,2.70,2.78
11,AUS,851.96,1052.58,926.45,1144.26,1394.28,1543.41,1573.70,1464.96,1349.03,1208.04,1323.42,1364.45
12,AUT,388.69,430.29,400.17,391.89,431.12,409.43,430.07,441.89,382.07,390.80,416.60,429.51
13,AZE,33.05,48.85,44.29,52.90,65.95,69.68,74.16,75.24,53.07,37.87,40.75,42.01
14,BHS,10.62,10.53,9.98,10.10,10.07,10.72,10.63,10.96,11.79,11.84,12.16,12.54
15,BHR,21.73,25.71,22.94,25.71,28.78,30.75,32.54,33.39,31.13,32.15,35.31,36.40
16,BGD,79.61,91.63,102.48,115.28,128.64,133.36,149.99,172.89,195.08,221.42,249.72,257.47
17,BRB,4.67,4.78,4.48,4.53,4.66,4.66,4.61,4.61,4.58,4.53,4.67,4.82
18,BLR,45.28,60.76,50.87,58.67,61.76,65.69,75.53,78.81,56.45,47.75,54.46,56.14
19,BEL,471.82,518.63,484.55,483.55,527.01,497.88,520.93,530.77,455.04,467.55,492.68,507.95
20,BLZ,1.29,1.37,1.34,1.40,1.49,1.56,1.61,1.69,1.76,1.81,1.86,1.92
21,BEN,5.97,7.13,7.10,6.97,7.81,8.15,9.16,9.71,8.29,8.57,9.25,9.53
22,BMU,5.90,6.11,5.81,5.74,5.55,5.54,5.57,0.00,0.00,0.00,0.00,0.00
23,BTN,1.20,1.26,1.26,1.59,1.82,1.82,1.80,1.96,2.06,2.22,2.53,2.61
24,BOL,13.12,16.67,17.34,19.65,23.96,27.08,30.66,33.00,33.00,33.94,37.51,38.67
25,BIH,15.78,19.11,17.61,17.18,18.64,17.23,18.18,18.56,16.21,16.91,18.05,18.61
26,BWA,10.94,10.95,10.27,12.79,15.35,14.42,14.90,16.25,14.41,15.65,17.41,17.95
27,BRA,1397.08,1695.82,1667.02,2208.87,2616.20,2465.19,2472.81,2455.99,1802.21,1793.99,2055.51,2119.23
28,VGB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
29,BRN,12.25,14.39,10.73,13.71,18.53,19.05,18.09,17.10,12.93,11.40,12.13,12.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,IDB,544.05,648.03,605.77,706.54,816.01,898.60,977.36,1058.85,1003.00,929.07,924.27,952.93
235,IDX,523.34,634.91,655.63,743.07,838.87,885.67,984.26,1057.66,1079.08,1100.91,1211.02,1248.56
236,IDA,1074.85,1291.30,1266.43,1456.43,1662.20,1793.84,1971.21,2127.20,2089.45,2033.20,2134.21,2200.37
237,LTE,9371.25,11650.66,11263.77,13513.14,16479.03,17632.22,19014.01,19703.59,18464.37,18471.55,20463.58,21097.95
238,LCN,3947.72,4588.22,4312.10,5347.33,6080.91,6143.79,6295.13,6417.07,5517.00,5381.03,5974.24,6159.44
239,LAC,3298.17,3836.47,3600.73,4481.07,5054.64,5075.68,5196.51,5356.67,4387.48,4284.87,4744.00,4891.07
240,TLA,3769.09,4402.42,4123.96,5152.71,5878.04,5934.95,6081.52,6199.46,5289.64,5148.50,5722.76,5900.17
241,LDC,467.82,580.71,582.49,667.27,770.56,823.71,893.03,969.74,959.83,961.39,1074.10,1107.40
242,LMY,14243.80,17088.28,16703.51,20251.03,23912.93,25539.08,27101.11,28155.30,26611.54,26726.02,29284.37,30192.18
243,LIC,282.49,342.25,360.54,392.93,445.37,482.12,528.95,566.46,556.85,538.61,575.40,593.24
244,LMC,3188.19,3584.99,3659.30,4487.00,5091.37,5340.63,5578.94,5874.70,5834.88,6054.67,6516.98,6719.01
245,MEA,2123.62,2647.70,2368.23,2767.87,3282.15,3575.25,3552.74,3567.70,3147.15,3155.75,3275.66,3377.21
246,MNA,1003.14,1235.37,1195.90,1383.52,1568.52,1728.45,1623.68,1598.39,1444.18,1459.01,1440.49,1485.15
247,TMN,997.69,1228.77,1188.67,1374.62,1558.06,1717.18,1611.13,1585.58,1431.38,1445.42,1425.78,1469.97
248,MIC,13961.75,16747.31,16350.05,19856.77,23462.55,25052.91,26571.36,27591.22,26060.68,26189.82,28708.95,29598.93
249,NAC,15948.51,16273.82,15795.70,16583.58,17312.12,17985.08,18539.72,19232.66,19686.26,20166.31,21049.98,21702.52
250,INX,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
251,OED,43034.32,45559.79,42617.38,44647.28,47978.63,47893.54,48473.42,49485.30,46749.58,47659.68,49629.78,51168.30
252,OSS,265.57,325.68,279.01,324.30,400.61,418.99,436.05,448.11,370.58,365.18,403.25,415.75
253,PSS,6.08,6.56,5.78,6.42,7.63,8.15,8.44,8.80,8.59,9.03,9.67,9.97
254,PST,40884.32,43196.31,40673.55,42412.40,45528.56,45463.01,45860.04,46789.82,44280.42,45260.10,47092.73,48552.60
255,PRE,751.32,947.45,855.76,1011.30,1183.40,1305.33,1428.91,1528.54,1344.61,1220.17,1295.51,1335.67
256,SST,332.55,401.34,342.95,393.98,476.59,497.72,515.83,529.41,450.03,441.87,481.74,496.67
257,SAS,1488.60,1515.56,1665.54,2042.06,2271.88,2297.28,2357.17,2581.87,2696.12,2902.95,3294.67,3396.80
258,TSA,1488.60,1515.56,1665.54,2042.06,2271.88,2297.28,2357.17,2581.87,2696.12,2902.95,3294.67,3396.80
259,SSF,1051.37,1205.11,1146.19,1366.25,1550.97,1633.38,1739.84,1826.90,1665.07,1543.18,1669.77,1721.53
260,SSA,1050.33,1204.15,1145.34,1365.29,1549.90,1632.32,1738.51,1825.56,1663.69,1541.75,1668.27,1719.99
261,TSS,1051.37,1205.11,1146.19,1366.25,1550.97,1633.38,1739.84,1826.90,1665.07,1543.18,1669.77,1721.53
262,UMC,10773.56,13162.32,12690.75,15369.77,18371.18,19712.28,20992.41,21716.52,20219.31,20124.28,22182.78,22870.45
263,WLD,57953.30,63574.89,60267.07,65965.88,73316.78,74993.71,77098.79,79188.46,74916.09,75997.38,80737.58,83240.44

In [475]:
economic_data = pd.melt(economic_data, id_vars=['Country Code'], var_name='year', value_name='gdp')
economic_data.head()

  Country Code  year       gdp
0          USA  2008  14477.64
1          AFG  2008      9.75
2          ALB  2008     10.68
3          DZA  2008    134.98
4          ASM  2008      0.52

In [476]:
# pickle clean df
economic_data.to_pickle("./economic_data_df.pkl")

### Employment to population ratio

In [420]:
# Percentage of population above 15 years old in employment
employment_data = pd.read_csv('/Users/laurengilson/Desktop/perm_data/employment_to_pop_ratio.csv')
employment_data

,Series Name,Series Code,Country Name,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,United States,USA,61.9879989624023,61.2270011901855,58.3740005493164,57.4620018005371,57.3759994506836,57.8219985961914,57.9029998779297,58.3699989318848,58.7400016784668,59.132999420166,59.1920013427734,59.1349983215332
1,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Afghanistan,AFG,48.2290000915527,47.4339981079102,48.2849998474121,47.6139984130859,47.6730003356934,48.2060012817383,48.3889999389648,48.7360000610352,49.1290016174316,49.4389991760254,49.4449996948242,49.4640007019043
2,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Albania,ALB,48.3730010986328,47.8709983825684,47.0299987792969,46.5639991760254,47.9259986877441,49.7229995727539,45.2610015869141,44.851001739502,46.8089981079102,47.7130012512207,48.2949981689453,47.4290008544922
3,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Algeria,DZA,36.4580001831055,37.4119987487793,37.8429985046387,38.1430015563965,38.2729988098145,38,39.3940010070801,37.1160011291504,36.8310012817383,37.1839981079102,37.2369995117188,37.2379989624023
4,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,American Samoa,ASM,..,..,..,..,..,..,..,..,..,..,..,..
5,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Andorra,AND,..,..,..,..,..,..,..,..,..,..,..,..
6,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Angola,AGO,64.6360015869141,66.4469985961914,68.3209991455078,70.1119995117188,72.1330032348633,72.1750030517578,72.1800003051758,72.1579971313477,72.0999984741211,71.6760025024414,71.2900009155273,70.9459991455078
7,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Antigua and Barbuda,ATG,..,..,..,..,..,..,..,..,..,..,..,..
8,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Argentina,ARG,56.3769989013672,56.0870018005371,55.9389991760254,55.1139984130859,56.4700012207031,56.310001373291,56.1139984130859,55.5089988708496,55.7089996337891,54.7490005493164,54.7509994506836,54.8489990234375
9,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Armenia,ARM,46.4039993286133,46.2179985046387,46.4039993286133,48.2480010986328,49.4379997253418,49.923999786377,50.9379997253418,49.9160003662109,48.8839988708496,49.0950012207031,49.173999786377,49.2939987182617
10,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Aruba,ABW,..,..,..,..,..,..,..,..,..,..,..,..
11,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Australia,AUS,62.4739990234375,62.8400001525879,61.8849983215332,62.1189994812012,62.2229995727539,61.8429985046387,61.3279991149902,60.8349990844727,61.1069984436035,61.1809997558594,61.1829986572266,61.1749992370605
12,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Austria,AUT,56.4949989318848,57.189998626709,56.7980003356934,57.068000793457,57.2849998474121,57.359001159668,57.2130012512207,56.7789993286133,56.6629981994629,56.7960014343262,57.0149993896484,56.9589996337891
13,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Azerbaijan,AZE,59.5740013122559,59.9850006103516,60.2750015258789,60.4049987792969,60.4869995117188,60.9379997253418,61.3390007019043,61.8580017089844,62.2649993896484,62.935001373291,62.7799987792969,62.5900001525879
14,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,"Bahamas, The",BHS,69.6999969482422,69.5059967041016,64.931999206543,64.9629974365234,64.7429962158203,65.1269989013672,63.4970016479492,65.2990036010742,66.6389999389648,66.0820007324219,66.2600021362305,66.5130004882813
15,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Bahrain,BHR,68.8539962768555,69.7009963989258,70.5859985351563,71.4039993286133,70.5390014648438,70.6380004882813,70.6559982299805,70.7060012817383,70.7750015258789,70.9919967651367,71.3300018310547,71.7519989013672
16,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Bangladesh,BGD,55.1129989624023,54.8019981384277,54.2490005493164,55.0610008239746,54.8079986572266,54.5670013427734,54.189998626709,54.109001159668,54.0270004272461,53.9799995422363,54.0320014953613,54.0830001831055
17,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Barbados,BRB,63.9280014038086,63.2360000610352,61.601001739502,60.7360000610352,60.3019981384277,59.007999420166,59.5950012207031,57.3079986572266,58.2159996032715,59.8600006103516,59.5309982299805,59.257999420166
18,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Belarus,BLR,61.0870018005371,61.5559997558594,62.0139999389648,62.2820014953613,62.9099998474121,63.25,63.5800018310547,63.7970008850098,63.9420013427734,63.935001373291,63.6990013122559,63.4059982299805
19,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Belgium,BEL,49.5769996643066,49.859001159668,49.1599998474121,49.4949989318848,49.2830009460449,49.1319999694824,48.9830017089844,48.9869995117188,48.9129981994629,49.0639991760254,49.3849983215332,49.640998840332
20,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Belize,BLZ,59.765998840332,60.5730018615723,59.9949989318848,59.5099983215332,59.234001159668,58.935001373291,60.0480003356934,59.4440002441406,59.8079986572266,61.5120010375977,60.8160018920898,61.1339988708496
21,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Benin,BEN,70.9189987182617,70.713996887207,70.4879989624023,70.3059997558594,68.9860000610352,68.9789962768555,68.9599990844727,68.9390029907227,68.9280014038086,68.9889984130859,69.1360015869141,69.2839965820313
22,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Bermuda,BMU,..,..,..,..,..,..,..,..,..,..,..,..
23,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Bhutan,BTN,68.8349990844727,68.931999206543,68.8639984130859,67.5080032348633,65.7799987792969,64.2160034179688,64.2009963989258,62.6920013427734,64.9739990234375,64.9049987792969,65.161003112793,65.390998840332
24,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Bolivia,BOL,68.1890029907227,70.1940002441406,69.9980010986328,70.1470031738281,70.2249984741211,67.5009994506836,67.6480026245117,69.8570022583008,64.9879989624023,65.2969970703125,65.2939987182617,65.3290023803711
25,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Bosnia and Herzegovina,BIH,34.5200004577637,37.1730003356934,36.7410011291504,35.0989990234375,34.7290000915527,34.2919998168945,34.326000213623,34.0299987792969,33.798999786377,35.0169982910156,34.685001373291,34.3709983825684
26,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Botswana,BWA,52.3790016174316,52.5369987487793,52.9580001831055,49.507999420166,53.173999786377,56.242000579834,58.6419982910156,58.9889984130859,59.3330001831055,59.3479995727539,59.4090003967285,59.435001373291
27,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Brazil,BRA,61.4119987487793,61.814998626709,61.451000213623,61.0589981079102,60.3230018615723,59.7239990234375,59.7389984130859,59.6839981079102,58.6889991760254,56.423999786377,55.1910018920898,55.859001159668
28,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,British Virgin Islands,VGB,..,..,..,..,..,..,..,..,..,..,..,..
29,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,Brunei Darussalam,BRN,63.2439994812012,63.2239990234375,63.2910003662109,63.3849983215332,63.5839996337891,63.7639999389648,63.9000015258789,63.2089996337891,62.9570007324219,62.5289993286133,62.3409996032715,62.2220001220703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Latin America & Caribbean (excluding high income),LAC,5.04232397628237,4.94639569701969,6.60239508678827,..,6.56678102075925,6.20685717113158,5.76150958493945,6.03071984911179,6.48763472003588,7.34077754095097,7.97154326776787,..
504,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Latin America & the Caribbean (IDA & IBRD coun...,TLA,5.213595817005,4.92346731958075,6.46873843111814,..,6.30051708774491,5.98583999012889,5.54026217918345,5.76573178077418,6.37541629152403,7.21829773919287,7.60315550691821,..
505,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Least developed countries: UN classification,LDC,..,..,..,..,..,..,..,..,..,..,..,..
506,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Low & middle income,LMY,..,..,..,..,..,..,..,..,..,..,..,..
507,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Low income,LIC,..,..,..,..,..,..,..,..,..,..,..,..
508,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Lower middle income,LMC,..,..,..,16.0687615356348,..,16.0977392888567,..,..,..,..,..,..
509,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Middle East & North Africa,MEA,..,..,..,..,..,..,..,..,..,..,..,..
510,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Middle East & North Africa (excluding high inc...,MNA,..,..,..,..,..,..,..,..,..,..,..,..
511,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Middle East & North Africa (IDA & IBRD countries),TMN,..,..,..,..,..,..,..,..,..,..,..,..
512,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Middle income,MIC,..,..,..,..,..,..,..,..,..,..,..,..
513,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,North America,NAC,2.72778806558843,3.23045382622806,5.04603339633274,5.2802219530828,5.18424608524148,5.01116042788689,4.50073753025605,3.94918162151718,3.38535798943952,3.2632202285441,3.09195745216736,..
514,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Not classified,INX,..,..,..,..,..,..,..,..,..,..,..,..
515,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,OECD members,OED,4.62956176435345,4.64665172298551,5.946351655379,6.28781163940917,6.75155278199479,7.28846511547796,7.66364577747855,7.86753801649332,7.16694769949277,7.22516618794644,7.02858502711895,..
516,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Other small states,OSS,..,..,..,..,..,..,..,..,..,..,..,..
517,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Pacific island small states,PSS,..,..,..,..,..,..,..,..,..,..,..,..
518,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Post-demographic dividend,PST,4.04947128296696,4.16560857943609,5.38091804480393,5.91422933525847,6.53600923854656,7.27959250523922,7.52670090866978,7.73865457415083,6.86099817646348,6.57973013520016,5.9580905697705,..
519,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Pre-demographic dividend,PRE,..,..,..,..,..,..,..,..,..,..,..,..
520,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Small states,SST,..,..,..,..,..,..,..,..,..,..,..,..
521,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,South Asia,SAS,..,..,..,15.6534928453694,..,16.5006856894438,..,..,..,..,..,..
522,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,South Asia (IDA & IBRD),TSA,..,..,..,15.6534928453694,..,16.5006856894438,..,..,..,..,..,..
523,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Sub-Saharan Africa,SSF,..,..,..,..,..,..,..,..,..,..,..,..
524,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Sub-Saharan Africa (excluding high income),SSA,..,..,..,..,..,..,..,..,..,..,..,..
525,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Sub-Saharan Africa (IDA & IBRD countries),TSS,..,..,..,..,..,..,..,..,..,..,..,..
526,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,Upper middle income,UMC,..,..,..,..,..,..,..,..,..,..,..,..
527,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,World,WLD,..,..,..,..,..,..,..,..,..,..,..,..
528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,Last Updated: 01/30/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Government expenditure on education

In [334]:
expenditure_data = pd.read_csv('/Users/laurengilson/Desktop/perm_data/gov_expenditure_education.csv')
expenditure_data.head()

,Series Name,Series Code,Country Name,Country Code,2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,United States,USA,..,..,..,5.42001,5.2239,5.19486,4.94379,4.98948,..,..,..,..
1,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,Afghanistan,AFG,..,..,..,3.46196,3.43785,2.52441,3.43437,3.6739,3.24202,4.20525,3.92675,..
2,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,Albania,ALB,3.26868,..,..,..,..,..,3.5393,..,3.43797,3.95464,2.18972,..
3,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,Algeria,DZA,..,4.33702,..,..,..,..,..,..,..,..,..,..
4,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GD.ZS,American Samoa,ASM,..,..,..,..,..,..,..,..,..,..,..,..

### Migrant population

In [587]:
immigration_data = pd.read_csv('/Users/laurengilson/Desktop/perm_data/percentage_of_immigrants.csv')
immigration_data

,Series Name,Series Code,Country Name,Country Code,2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,International migrant stock (% of population),SM.POP.TOTL.ZS,United States,USA,13.2566831184215,..,..,..,..,14.2584836388032,..,..,..,..,14.4906535240608,..,..,..
1,International migrant stock (% of population),SM.POP.TOTL.ZS,Afghanistan,AFG,0.357787647744167,..,..,..,..,0.365657832373532,..,..,..,..,1.17554692684705,..,..,..
2,International migrant stock (% of population),SM.POP.TOTL.ZS,Albania,ALB,2.10043436900991,..,..,..,..,1.8189568635262,..,..,..,..,1.98903641031678,..,..,..
3,International migrant stock (% of population),SM.POP.TOTL.ZS,Algeria,DZA,0.744071903334288,..,..,..,..,0.67977278044533,..,..,..,..,0.611072022730303,..,..,..
4,International migrant stock (% of population),SM.POP.TOTL.ZS,American Samoa,ASM,40.9915929428083,..,..,..,..,42.3376950176145,..,..,..,..,41.8020094349815,..,..,..
5,International migrant stock (% of population),SM.POP.TOTL.ZS,Andorra,AND,61.9258091919776,..,..,..,..,61.6602897451995,..,..,..,..,59.713649198984,..,..,..
6,International migrant stock (% of population),SM.POP.TOTL.ZS,Angola,AGO,0.342372570625194,..,..,..,..,0.36074065005042,..,..,..,..,0.427004679966497,..,..,..
7,International migrant stock (% of population),SM.POP.TOTL.ZS,Antigua and Barbuda,ATG,29.9654817416581,..,..,..,..,30.2775325851455,..,..,..,..,30.5855061099131,..,..,..
8,International migrant stock (% of population),SM.POP.TOTL.ZS,Argentina,ARG,4.27402481680457,..,..,..,..,4.38095838778833,..,..,..,..,4.80529233472193,..,..,..
9,International migrant stock (% of population),SM.POP.TOTL.ZS,Armenia,ARM,15.5599308372337,..,..,..,..,7.47630501272821,..,..,..,..,6.33589288838696,..,..,..
10,International migrant stock (% of population),SM.POP.TOTL.ZS,Aruba,ABW,32.5299157261249,..,..,..,..,33.7874149827259,..,..,..,..,34.7621018587146,..,..,..
11,International migrant stock (% of population),SM.POP.TOTL.ZS,Australia,AUS,24.0601862004287,..,..,..,..,26.5443142431553,..,..,..,..,28.2184096915625,..,..,..
12,International migrant stock (% of population),SM.POP.TOTL.ZS,Austria,AUT,13.798295003994,..,..,..,..,15.2048871387536,..,..,..,..,17.465726250517,..,..,..
13,International migrant stock (% of population),SM.POP.TOTL.ZS,Azerbaijan,AZE,3.52920651358258,..,..,..,..,3.04290391106797,..,..,..,..,2.70906158396255,..,..,..
14,International migrant stock (% of population),SM.POP.TOTL.ZS,"Bahamas, The",BHS,13.8484341352739,..,..,..,..,15.1694703877172,..,..,..,..,15.2843030882508,..,..,..
15,International migrant stock (% of population),SM.POP.TOTL.ZS,Bahrain,BHR,46.5987861787699,..,..,..,..,52.1561952210345,..,..,..,..,51.12678500505,..,..,..
16,International migrant stock (% of population),SM.POP.TOTL.ZS,Bangladesh,BGD,0.816273820343876,..,..,..,..,0.887465112122783,..,..,..,..,0.883753735396142,..,..,..
17,International migrant stock (% of population),SM.POP.TOTL.ZS,Barbados,BRB,11.1761120822735,..,..,..,..,11.741413476603,..,..,..,..,12.1299016589554,..,..,..
18,International migrant stock (% of population),SM.POP.TOTL.ZS,Belarus,BLR,11.4824820322685,..,..,..,..,11.4871890605704,..,..,..,..,11.4040105621143,..,..,..
19,International migrant stock (% of population),SM.POP.TOTL.ZS,Belgium,BEL,8.24567795515686,..,..,..,..,9.63262689092329,..,..,..,..,12.2835331942319,..,..,..
20,International migrant stock (% of population),SM.POP.TOTL.ZS,Belize,BLZ,14.6230394769821,..,..,..,..,14.4150194801762,..,..,..,..,14.990801225761,..,..,..
21,International migrant stock (% of population),SM.POP.TOTL.ZS,Benin,BEN,2.09595957744231,..,..,..,..,2.20054095786262,..,..,..,..,2.25554096484421,..,..,..
22,International migrant stock (% of population),SM.POP.TOTL.ZS,Bermuda,BMU,28.0633867698544,..,..,..,..,29.5274728711261,..,..,..,..,30.8463970066447,..,..,..
23,International migrant stock (% of population),SM.POP.TOTL.ZS,Bhutan,BTN,6.18570158316735,..,..,..,..,6.72270307644888,..,..,..,..,6.59576939457687,..,..,..
24,International migrant stock (% of population),SM.POP.TOTL.ZS,Bolivia,BOL,1.18071471896316,..,..,..,..,1.23858606033628,..,..,..,..,1.33326744185504,..,..,..
25,International migrant stock (% of population),SM.POP.TOTL.ZS,Bosnia and Herzegovina,BIH,1.23316856129726,..,..,..,..,1.01145737783482,..,..,..,..,0.913364839954483,..,..,..
26,International migrant stock (% of population),SM.POP.TOTL.ZS,Botswana,BWA,4.76549662205479,..,..,..,..,5.9043934777821,..,..,..,..,7.10033436685768,..,..,..
27,International migrant stock (% of population),SM.POP.TOTL.ZS,Brazil,BRA,0.338807605548494,..,..,..,..,0.298351263974025,..,..,..,..,0.34331320024167,..,..,..
28,International migrant stock (% of population),SM.POP.TOTL.ZS,British Virgin Islands,VGB,59.5968751348785,..,..,..,..,57.1502038717261,..,..,..,..,57.4692034399177,..,..,..
29,International migrant stock (% of population),SM.POP.TOTL.ZS,Brunei Darussalam,BRN,27.2019873497122,..,..,..,..,25.5750034324768,..,..,..,..,24.2759719084662,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,International migrant stock (% of population),SM.POP.TOTL.ZS,Latin America & Caribbean (excluding high income),LAC,0.840025761152732,..,..,..,..,0.928274042780619,..,..,..,..,0.981475518739833,..,..,..
240,International migrant stock (% of population),SM.POP.TOTL.ZS,Latin America & the Caribbean (IDA & IBRD coun...,TLA,1.16531492881634,..,..,..,..,1.2668610191842,..,..,..,..,1.35684986227982,..,..,..
241,International migrant stock (% of population),SM.POP.TOTL.ZS,Least developed countries: UN classification,LDC,1.30162672523344,..,..,..,..,1.16361351775642,..,..,..,..,1.25091234931097,..,..,..
242,International migrant stock (% of population),SM.POP.TOTL.ZS,Low & middle income,LMY,1.30044926037362,..,..,..,..,1.31106517350438,..,..,..,..,1.37690262227679,..,..,..
243,International migrant stock (% of population),SM.POP.TOTL.ZS,Low income,LIC,1.70400081614669,..,..,..,..,1.60537995051158,..,..,..,..,1.57107211480999,..,..,..
244,International migrant stock (% of population),SM.POP.TOTL.ZS,Lower middle income,LMC,0.98539727943911,..,..,..,..,0.938393579031547,..,..,..,..,0.891268880071905,..,..,..
245,International migrant stock (% of population),SM.POP.TOTL.ZS,Middle East & North Africa,MEA,6.68601050141096,..,..,..,..,8.4174214286814,..,..,..,..,9.25582667673871,..,..,..
246,International migrant stock (% of population),SM.POP.TOTL.ZS,Middle East & North Africa (excluding high inc...,MNA,2.80481493630262,..,..,..,..,3.08895583602717,..,..,..,..,3.28962157824629,..,..,..
247,International migrant stock (% of population),SM.POP.TOTL.ZS,Middle East & North Africa (IDA & IBRD countries),TMN,2.75397344174231,..,..,..,..,3.0515904115962,..,..,..,..,3.2630247051241,..,..,..
248,International migrant stock (% of population),SM.POP.TOTL.ZS,Middle income,MIC,1.25649289871864,..,..,..,..,1.27586979134595,..,..,..,..,1.35216298191598,..,..,..
249,International migrant stock (% of population),SM.POP.TOTL.ZS,North America,NAC,13.8103628062295,..,..,..,..,14.8838882630412,..,..,..,..,15.2275859859335,..,..,..
250,International migrant stock (% of population),SM.POP.TOTL.ZS,Not classified,INX,..,..,..,..,..,..,..,..,..,..,..,..,..,..
251,International migrant stock (% of population),SM.POP.TOTL.ZS,OECD members,OED,8.49721707410044,..,..,..,..,9.54909872538317,..,..,..,..,10.0383815891427,..,..,..
252,International migrant stock (% of population),SM.POP.TOTL.ZS,Other small states,OSS,11.0764935453057,..,..,..,..,14.5359494128503,..,..,..,..,15.0339188013467,..,..,..
253,International migrant stock (% of population),SM.POP.TOTL.ZS,Pacific island small states,PSS,2.16427726235105,..,..,..,..,2.08185601392565,..,..,..,..,2.08201123147697,..,..,..
254,International migrant stock (% of population),SM.POP.TOTL.ZS,Post-demographic dividend,PST,10.2563571755716,..,..,..,..,11.5504611521559,..,..,..,..,12.0885545704741,..,..,..
255,International migrant stock (% of population),SM.POP.TOTL.ZS,Pre-demographic dividend,PRE,1.66438534605621,..,..,..,..,1.50489534977394,..,..,..,..,1.57503391560486,..,..,..
256,International migrant stock (% of population),SM.POP.TOTL.ZS,Small states,SST,9.03250170168427,..,..,..,..,11.8112119550695,..,..,..,..,12.3749185140506,..,..,..
257,International migrant stock (% of population),SM.POP.TOTL.ZS,South Asia,SAS,0.738817569205888,..,..,..,..,0.71102896315613,..,..,..,..,0.654289827376112,..,..,..
258,International migrant stock (% of population),SM.POP.TOTL.ZS,South Asia (IDA & IBRD),TSA,0.738817569205888,..,..,..,..,0.71102896315613,..,..,..,..,0.654289827376112,..,..,..
259,International migrant stock (% of population),SM.POP.TOTL.ZS,Sub-Saharan Africa,SSF,1.79944886806839,..,..,..,..,1.72568465310403,..,..,..,..,1.87686892023959,..,..,..
260,International migrant stock (% of population),SM.POP.TOTL.ZS,Sub-Saharan Africa (excluding high income),SSA,1.79853725709988,..,..,..,..,1.7246061102152,..,..,..,..,1.87580658799565,..,..,..
261,International migrant stock (% of population),SM.POP.TOTL.ZS,Sub-Saharan Africa (IDA & IBRD countries),TSS,1.79944886806839,..,..,..,..,1.72568465310403,..,..,..,..,1.87686892023959,..,..,..
262,International migrant stock (% of population),SM.POP.TOTL.ZS,Upper middle income,UMC,1.54219168841722,..,..,..,..,1.64638725166325,..,..,..,..,1.87665043036273,..,..,..
263,International migrant stock (% of population),SM.POP.TOTL.ZS,World,WLD,2.94241113643821,..,..,..,..,3.20539093902952,..,..,..,..,3.33804873729344,..,..,..
264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,Last Updated: 01/30/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Net migration

In [591]:
migration_data = pd.read_csv('/Users/laurengilson/Desktop/perm_data/net_migration.csv')
migration_data

,Series Name,Series Code,Country Name,Country Code,2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],...,2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,Net migration,SM.POP.NETM,United States,USA,5206538,..,..,..,..,5033689,...,..,..,..,4500000,..,..,..,..,4500000,..
1,Net migration,SM.POP.NETM,Afghanistan,AFG,929118,..,..,..,..,-777497,...,..,..,..,448007,..,..,..,..,-299999,..
2,Net migration,SM.POP.NETM,Albania,ALB,-176774,..,..,..,..,-217358,...,..,..,..,-93425,..,..,..,..,-40000,..
3,Net migration,SM.POP.NETM,Algeria,DZA,-205228,..,..,..,..,-357340,...,..,..,..,-143268,..,..,..,..,-50002,..
4,Net migration,SM.POP.NETM,American Samoa,ASM,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
5,Net migration,SM.POP.NETM,Andorra,AND,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
6,Net migration,SM.POP.NETM,Angola,AGO,172594,..,..,..,..,85286,...,..,..,..,87322,..,..,..,..,0,..
7,Net migration,SM.POP.NETM,Antigua and Barbuda,ATG,-282,..,..,..,..,-92,...,..,..,..,-56,..,..,..,..,-56,..
8,Net migration,SM.POP.NETM,Argentina,ARG,-90000,..,..,..,..,-84998,...,..,..,..,30000,..,..,..,..,24002,..
9,Net migration,SM.POP.NETM,Armenia,ARM,-160521,..,..,..,..,-183361,...,..,..,..,-30535,..,..,..,..,-24989,..
10,Net migration,SM.POP.NETM,Aruba,ABW,6263,..,..,..,..,-441,...,..,..,..,1253,..,..,..,..,1004,..
11,Net migration,SM.POP.NETM,Australia,AUS,575104,..,..,..,..,1122688,...,..,..,..,913107,..,..,..,..,849966,..
12,Net migration,SM.POP.NETM,Austria,AUT,178117,..,..,..,..,153763,...,..,..,..,267172,..,..,..,..,99999,..
13,Net migration,SM.POP.NETM,Azerbaijan,AZE,36524,..,..,..,..,53580,...,..,..,..,0,..,..,..,..,0,..
14,Net migration,SM.POP.NETM,"Bahamas, The",BHS,15483,..,..,..,..,14363,...,..,..,..,9672,..,..,..,..,5000,..
15,Net migration,SM.POP.NETM,Bahrain,BHR,155500,..,..,..,..,272000,...,..,..,..,42000,..,..,..,..,235000,..
16,Net migration,SM.POP.NETM,Bangladesh,BGD,-1541457,..,..,..,..,-3570954,...,..,..,..,-2526483,..,..,..,..,-2350001,..
17,Net migration,SM.POP.NETM,Barbados,BRB,-77,..,..,..,..,2050,...,..,..,..,2180,..,..,..,..,2072,..
18,Net migration,SM.POP.NETM,Belarus,BLR,-6382,..,..,..,..,63933,...,..,..,..,75799,..,..,..,..,10000,..
19,Net migration,SM.POP.NETM,Belgium,BEL,219560,..,..,..,..,294270,...,..,..,..,258672,..,..,..,..,240000,..
20,Net migration,SM.POP.NETM,Belize,BLZ,5797,..,..,..,..,8722,...,..,..,..,7594,..,..,..,..,6832,..
21,Net migration,SM.POP.NETM,Benin,BEN,25005,..,..,..,..,-48776,...,..,..,..,-42268,..,..,..,..,-10000,..
22,Net migration,SM.POP.NETM,Bermuda,BMU,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
23,Net migration,SM.POP.NETM,Bhutan,BTN,29002,..,..,..,..,16829,...,..,..,..,10000,..,..,..,..,0,..
24,Net migration,SM.POP.NETM,Bolivia,BOL,-89995,..,..,..,..,-84003,...,..,..,..,-61794,..,..,..,..,-50005,..
25,Net migration,SM.POP.NETM,Bosnia and Herzegovina,BIH,-6000,..,..,..,..,-59246,...,..,..,..,-161371,..,..,..,..,-2506,..
26,Net migration,SM.POP.NETM,Botswana,BWA,21278,..,..,..,..,18730,...,..,..,..,15000,..,..,..,..,15000,..
27,Net migration,SM.POP.NETM,Brazil,BRA,0,..,..,..,..,0,...,..,..,..,15924,..,..,..,..,30000,..
28,Net migration,SM.POP.NETM,British Virgin Islands,VGB,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
29,Net migration,SM.POP.NETM,Brunei Darussalam,BRN,3347,..,..,..,..,-2089,...,..,..,..,2030,..,..,..,..,1760,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,Net migration,SM.POP.NETM,Latin America & Caribbean (excluding high income),LAC,-5337998,..,..,..,..,-2319942,...,..,..,..,-1848874,..,..,..,..,-1731412,..
240,Net migration,SM.POP.NETM,Latin America & the Caribbean (IDA & IBRD coun...,TLA,-5346329,..,..,..,..,-2205983,...,..,..,..,-1671733,..,..,..,..,-1500234,..
241,Net migration,SM.POP.NETM,Least developed countries: UN classification,LDC,-4028366,..,..,..,..,-9450809,...,..,..,..,-5849388,..,..,..,..,-5247506,..
242,Net migration,SM.POP.NETM,Low & middle income,LMY,-18227834,..,..,..,..,-22296592,...,..,..,..,-15873728,..,..,..,..,-14639694,..
243,Net migration,SM.POP.NETM,Low income,LIC,-1397124,..,..,..,..,-2792486,...,..,..,..,-6481500,..,..,..,..,-3675622,..
244,Net migration,SM.POP.NETM,Lower middle income,LMC,-12139540,..,..,..,..,-16983797,...,..,..,..,-12173175,..,..,..,..,-10438795,..
245,Net migration,SM.POP.NETM,Middle East & North Africa,MEA,744774,..,..,..,..,5148017,...,..,..,..,1023970,..,..,..,..,-330734,..
246,Net migration,SM.POP.NETM,Middle East & North Africa (excluding high inc...,MNA,-1665598,..,..,..,..,-1318048,...,..,..,..,-3206474,..,..,..,..,-2416237,..
247,Net migration,SM.POP.NETM,Middle East & North Africa (IDA & IBRD countries),TMN,-1475598,..,..,..,..,-1228047,...,..,..,..,-3162723,..,..,..,..,-2383421,..
248,Net migration,SM.POP.NETM,Middle income,MIC,-16830710,..,..,..,..,-19504106,...,..,..,..,-9392228,..,..,..,..,-10964072,..
249,Net migration,SM.POP.NETM,North America,NAC,6233240,..,..,..,..,6263594,...,..,..,..,5645721,..,..,..,..,5600000,..
250,Net migration,SM.POP.NETM,Not classified,INX,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
251,Net migration,SM.POP.NETM,OECD members,OED,12384153,..,..,..,..,15211742,...,..,..,..,12486403,..,..,..,..,13232046,..
252,Net migration,SM.POP.NETM,Other small states,OSS,320214,..,..,..,..,1097149,...,..,..,..,743771,..,..,..,..,446398,..
253,Net migration,SM.POP.NETM,Pacific island small states,PSS,-105941,..,..,..,..,-75792,...,..,..,..,-71074,..,..,..,..,-56855,..
254,Net migration,SM.POP.NETM,Post-demographic dividend,PST,15405871,..,..,..,..,15844854,...,..,..,..,11408223,..,..,..,..,12156364,..
255,Net migration,SM.POP.NETM,Pre-demographic dividend,PRE,-552656,..,..,..,..,-3653097,...,..,..,..,-1589003,..,..,..,..,-2004805,..
256,Net migration,SM.POP.NETM,Small states,SST,54465,..,..,..,..,879195,...,..,..,..,552480,..,..,..,..,269888,..
257,Net migration,SM.POP.NETM,South Asia,SAS,-4439248,..,..,..,..,-10167795,...,..,..,..,-6663834,..,..,..,..,-6962017,..
258,Net migration,SM.POP.NETM,South Asia (IDA & IBRD),TSA,-4439248,..,..,..,..,-10167795,...,..,..,..,-6663834,..,..,..,..,-6962017,..
259,Net migration,SM.POP.NETM,Sub-Saharan Africa,SSF,-1080073,..,..,..,..,-1983360,...,..,..,..,-2046131,..,..,..,..,-1724595,..
260,Net migration,SM.POP.NETM,Sub-Saharan Africa (excluding high income),SSA,-1082586,..,..,..,..,-1980849,...,..,..,..,-2043930,..,..,..,..,-1723595,..
261,Net migration,SM.POP.NETM,Sub-Saharan Africa (IDA & IBRD countries),TSS,-1080073,..,..,..,..,-1983360,...,..,..,..,-2046131,..,..,..,..,-1724595,..
262,Net migration,SM.POP.NETM,Upper middle income,UMC,-4691170,..,..,..,..,-2520309,...,..,..,..,2780947,..,..,..,..,-525277,..
263,Net migration,SM.POP.NETM,World,WLD,0,..,..,..,..,0,...,..,..,..,0,..,..,..,..,0,..
264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,Last Updated: 01/30/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Function to clean all World Bank data

In [5]:
def CleanEconomic(data):
    
    # Read data
    economic_data = pd.read_csv(f'/Users/laurengilson/Desktop/perm_data/{data}.csv')
    
    # remove last 5 rows
    economic_data = economic_data[:-5]

    # drop unnecessary columns 
    economic_data.drop(['Series Name', 'Series Code', 'Country Name'], axis=1, inplace=True)
    
    # Turn to strings and replace '..' with '0'
    for column in list(economic_data.columns):
        economic_data[column] = list(map(str, economic_data[column]))
        economic_data[column] = [x.replace('..', '0') for x in economic_data[column]]
    
    if data == 'migrant_pop':
        
        economic_data['2007 [YR2007]'] = economic_data['2005 [YR2005]']
        economic_data.drop(['2005 [YR2005]', '2006 [YR2006]'], axis=1, inplace=True)
    
    elif data == 'net_migration':
        
        for idx, column in enumerate(list(economic_data.columns)[2:]):
            economic_data[column] = economic_data[column].astype(float)
            economic_data[column] = economic_data[column].replace(to_replace=0, value=economic_data.iloc[-1][column])
            economic_data[column] = economic_data[column].replace(0, np.nan) # replace 0 with NaNs
            economic_data.loc[economic_data[column].isnull(), column] = economic_data.iloc[:,economic_data.columns.get_loc(column)-1] # rest of nans with value from prev column
        
        economic_data.drop(['2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]'], axis=1, inplace=True)
    else: 
        None
    
    # dict of new columns 
    years = ['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
    col_list = list(economic_data.columns[1:])
    new_cols = dict(zip(col_list, years))

    # Change column head to fiscal years 
    economic_data.rename(columns=new_cols, inplace=True)
    
    
    if data == gdp:
        
        # Change 2019 - to have 3.1% growth on 2018.
        economic_data['2019'] = economic_data['2018'].astype(float) * 1.031
        
        # Put data in billions & round to 2dp 
        for column in list(economic_data.columns)[1:]:
            economic_data[column] = economic_data[column].astype(float)/1000000000
            economic_data[column] = economic_data[column].apply(lambda x: round(x, 2))
        
        # Transform df
        economic_data = pd.melt(economic_data, id_vars=['Country Code'], var_name='year', value_name='gdp')
        
        return economic_data
    
    elif data == employment:
        
        for column in list(economic_data.columns)[1:]:
            economic_data[column] = economic_data[column].astype(float)
            economic_data[column] = economic_data[column].apply(lambda x: round(x, 2))
            economic_data[column] = economic_data[column].replace(to_replace=0, value=economic_data[column].mean())
        
        # Transform df
        economic_data = pd.melt(economic_data, id_vars=['Country Code'], var_name='year', value_name='employment')
        
        return economic_data
    
    elif data == gov_expen:

        for idx, column in enumerate(list(economic_data.columns)[1:]):
            economic_data[column] = economic_data[column].astype(float)
            economic_data[column] = economic_data[column].replace(to_replace=0, value=economic_data.iloc[-1][column])
            economic_data[column] = economic_data[column].replace(0, np.nan) # replace 0 with NaNs
            economic_data.loc[economic_data[column].isnull(), column] = economic_data.iloc[:,economic_data.columns.get_loc(column)-1] # rest of nans with value from prev column
        
        # Transform df
        economic_data = pd.melt(economic_data, id_vars=['Country Code'], var_name='year', value_name='gov_expen')

        return economic_data
    
    elif data == 'employment_to_pop_ratio':
        
        for idx, column in enumerate(list(economic_data.columns)[1:]):
            economic_data[column] = economic_data[column].astype(float)
            economic_data[column] = economic_data[column].apply(lambda x: round(x, 2))
            economic_data[column] = economic_data[column].replace(0, np.nan) # replace 0 with NaNs
            
        for idx, column in enumerate(list(economic_data.columns)[2:]):
            economic_data.loc[economic_data[column].isnull(), column] = economic_data.iloc[:,economic_data.columns.get_loc(column)-1]
            economic_data.fillna(0)
            economic_data.astype(float)
        # Transform df
        economic_data = pd.melt(economic_data, id_vars=['Country Code'], var_name='year', value_name='migrant_pop')

        return economic_data
    
    else: 
        # Transform df
        economic_data = pd.melt(economic_data, id_vars=['Country Code'], var_name='year', value_name='migrant_pop')

        return economic_data

In [6]:
CleanEconomic('employment_to_pop_ratio')

NameError: name 'migrant_pop' is not defined

In [614]:
economic_list = ['GDP_data','employment_to_pop_ratio','gov_expenditure_education','percentage_of_immigrants','net_migration']

In [615]:
cleaned_dfs = []

for data in economic_list:
    cleaned_dfs.append(CleanEconomic(data))